"""Initial migration.

Revision ID: 165a5f0bcdb2
Revises: 
Create Date: 2025-07-03 10:02:34.944928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165a5f0bcdb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pdf_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('statement_period', sa.String(), nullable=False),
    sa.Column('request_date', sa.String(), nullable=False),
    sa.Column('statement_duration_months', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pdf_id'], ['pdf_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_details_pdf_id'), ['pdf_id'], unique=False)

    op.create_table('document_extras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pdf_id', sa.Integer(), nullable=False),
    sa.Column('note_type', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['pdf_id'], ['pdf_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_extras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_extras_pdf_id'), ['pdf_id'], unique=False)

    op.create_table('received_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pdf_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('total_received', sa.Float(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pdf_id'], ['pdf_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('received_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_received_summary_pdf_id'), ['pdf_id'], unique=False)

    op.create_table('spending_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pdf_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('total_spent', sa.Float(), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pdf_id'], ['pdf_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spending_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spending_summary_pdf_id'), ['pdf_id'], unique=False)

    op.create_table('total_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pdf_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('total_paid_in', sa.String(), nullable=False),
    sa.Column('total_paid_out', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['pdf_id'], ['pdf_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('total_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_total_summary_pdf_id'), ['pdf_id'], unique=False)

    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pdf_id', sa.Integer(), nullable=False),
    sa.Column('receipt_no', sa.String(), nullable=False),
    sa.Column('completion_time', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=False),
    sa.Column('transaction_status', sa.String(), nullable=False),
    sa.Column('paid_in', sa.Float(), nullable=True),
    sa.Column('withdraw', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['pdf_id'], ['pdf_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_pdf_id'), ['pdf_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_pdf_id'))

    op.drop_table('transaction')
    with op.batch_alter_table('total_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_total_summary_pdf_id'))

    op.drop_table('total_summary')
    with op.batch_alter_table('spending_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spending_summary_pdf_id'))

    op.drop_table('spending_summary')
    with op.batch_alter_table('received_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_received_summary_pdf_id'))

    op.drop_table('received_summary')
    with op.batch_alter_table('document_extras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_extras_pdf_id'))

    op.drop_table('document_extras')
    with op.batch_alter_table('customer_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_details_pdf_id'))

    op.drop_table('customer_details')
    op.drop_table('pdf_document')
    # ### end Alembic commands ###
