"""Make uploaded_at non-nullable

Revision ID: 78a7847ddb64
Revises: 165a5f0bcdb2
Create Date: 2025-07-15 11:03:48.838041

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78a7847ddb64'
down_revision = '165a5f0bcdb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_document', schema=None) as batch_op:
        batch_op.alter_column('uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdf_document', schema=None) as batch_op:
        batch_op.alter_column('uploaded_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
